# Generated by Django 5.0.3 on 2024-03-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flow",
            name="edges",
        ),
        migrations.RemoveField(
            model_name="flow",
            name="nodes",
        ),
        migrations.AlterField(
            model_name="node",
            name="name",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="type",
            field=models.CharField(
                choices=[("actorNode", "Actor Node"), ("trohpyNode", "Trohpy Node")],
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="edges",
            field=models.ManyToManyField(to="flows.edge"),
        ),
        migrations.AddField(
            model_name="flow",
            name="nodes",
            field=models.ManyToManyField(to="flows.node"),
        ),
    ]
